### ISSUE TITLE
Having trouble running the script

### ISSUE THREAD

**Issue by gdneye** [Reavershark/poe-timeless-jewel-finder#1]
Hey I was wondering if you could help me out.  I was trying to run this.  I think I successfully installed a D compiler (I installed DMD from https://dlang.org/download.html).  As far as I can tell that looks good.  I then ran the program and ran into the attached error message.

I've never worked with D before and I'm not a programmer.  But I have managed to install a few programs from source before so I'm not entirely useless =).
![Untitled](https://user-images.githubusercontent.com/26702989/108576334-da905700-72e2-11eb-830e-5a5d39d7f97e.png)

**Comment by jnms-me** [comment]
This was meant to run on a linux machine, it crashes because `unzip` cloudn't be found.

Either you run this in linux or you wait a day for me to remove the os-specific stuff :)

Glad that you gave some feedback, didn't expect this tool to be of much use.

**Comment by gdneye** [comment]
Oh I can run it on a Linux machine.  I have windows on my main PC mostly for gaming and Excel, but my laptop runs Pop OS.  It's 11:50 here rn and I just saw your message so I'll try it tomorrow.

I think it looks like a pretty useful tool.  Hopefully it works out for me.  I kind of enjoy being a beta tester for this kind of thing so if it helps me do what I want (I'm looking for timeless jewels that have a decent amount of increased non-curse effect) then I'll be happy to let you know any issues I run across.

Thanks!

**Comment by gdneye** [comment]
Alright man I got it working on Pop OS no problem.  So far I haven't ran into any issues.  Thanks for putting this program together!
